// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1A6EcBePCkiL9_kLwb-Tt9Ea2GQDXITE',
    appId: '1:302928066328:web:8e824d82282e39fa49906d',
    messagingSenderId: '302928066328',
    projectId: 'lol-beach',
    authDomain: 'lol-beach.firebaseapp.com',
    storageBucket: 'lol-beach.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_lFFAo6LlLUJubqpfTemNk_6gyB4mh_g',
    appId: '1:302928066328:android:62ffae50f1e469a649906d',
    messagingSenderId: '302928066328',
    projectId: 'lol-beach',
    storageBucket: 'lol-beach.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOpEDm7rjYVp-FjMXclHxWHEbEzxzZp2g',
    appId: '1:302928066328:ios:b87e43ce938922cc49906d',
    messagingSenderId: '302928066328',
    projectId: 'lol-beach',
    storageBucket: 'lol-beach.appspot.com',
    iosBundleId: 'com.example.coastalTourismApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOpEDm7rjYVp-FjMXclHxWHEbEzxzZp2g',
    appId: '1:302928066328:ios:b87e43ce938922cc49906d',
    messagingSenderId: '302928066328',
    projectId: 'lol-beach',
    storageBucket: 'lol-beach.appspot.com',
    iosBundleId: 'com.example.coastalTourismApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1A6EcBePCkiL9_kLwb-Tt9Ea2GQDXITE',
    appId: '1:302928066328:web:a7ea7891b4ad714449906d',
    messagingSenderId: '302928066328',
    projectId: 'lol-beach',
    authDomain: 'lol-beach.firebaseapp.com',
    storageBucket: 'lol-beach.appspot.com',
  );

}